export type UserRole = 'tenant' | 'owner' | 'broker';
export type Property = { id:string; title:string; locality:string; address:string; price:number; beds:number; baths:number; area:number; type:string; furnishing:string; image:string; verified:boolean; premium:boolean; highlights:string[]; description:string; owner:string; phone:string; availableFrom:string; rating:number };
export const localities = ['Fateh Sagar','Hiran Magri','Sector 14','Shobhagpura','Bhuwana','Sukher','Saheli Nagar','University Road','Ambamata','Badi Lake'];
export const properties: Property[] = [
{id:'lakeview-palace-apartment',title:'Lakeview Palace Apartment',locality:'Fateh Sagar',address:'Near Rani Road, Fateh Sagar Lake',price:42000,beds:3,baths:3,area:1850,type:'Apartment',furnishing:'Fully furnished',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',verified:true,premium:true,highlights:['Lake-facing balcony','Modular kitchen','Covered parking','24x7 security'],description:'A refined lake-facing home with premium interiors, sunrise views and quick access to cafes, schools and medical facilities around Fateh Sagar.',owner:'Arvind Singh',phone:'+91 98290 11223',availableFrom:'2026-09-01',rating:4.9},
{id:'hiran-magri-family-villa',title:'Royal Family Villa',locality:'Hiran Magri',address:'Sector 11, Hiran Magri',price:58000,beds:4,baths:4,area:2600,type:'Villa',furnishing:'Semi furnished',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',verified:true,premium:true,highlights:['Private garden','Servant room','Solar backup','Pet friendly'],description:'Spacious villa ideal for families seeking privacy, greenery and fast connectivity to the old city, railway station and schools.',owner:'Mahima Estates',phone:'+91 94141 44556',availableFrom:'2026-08-30',rating:4.8},
{id:'shobhagpura-studio',title:'Designer Studio for Professionals',locality:'Shobhagpura',address:'100 Feet Road, Shobhagpura',price:18000,beds:1,baths:1,area:540,type:'Studio',furnishing:'Fully furnished',image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',verified:true,premium:false,highlights:['Work desk','High-speed Wi-Fi','Housekeeping','Walk to cafes'],description:'Compact and elegant studio for working professionals near offices, gyms and restaurants on 100 Feet Road.',owner:'Nidhi Jain',phone:'+91 95877 77720',availableFrom:'2026-08-25',rating:4.7},
{id:'bhuwana-modern-2bhk',title:'Sunlit Modern 2 BHK',locality:'Bhuwana',address:'Celebration Mall Road, Bhuwana',price:26000,beds:2,baths:2,area:1180,type:'Apartment',furnishing:'Semi furnished',image:'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',verified:false,premium:false,highlights:['Gated society','Pool access','Near mall','Power backup'],description:'A bright apartment in a secure community near Celebration Mall, suitable for couples and small families.',owner:'Lakecity Brokers',phone:'+91 97833 31010',availableFrom:'2026-09-05',rating:4.5},
{id:'sukher-warehouse-office',title:'Sukher Warehouse + Office',locality:'Sukher',address:'Sukher Industrial Area',price:75000,beds:0,baths:2,area:4200,type:'Commercial',furnishing:'Unfurnished',image:'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1200&q=80',verified:true,premium:false,highlights:['Truck access','Office cabin','3-phase power','Main road'],description:'Commercial warehouse with attached office space, loading access and excellent connectivity to NH-27.',owner:'Rathore Realty',phone:'+91 90019 88001',availableFrom:'2026-09-10',rating:4.6},
{id:'university-road-pg',title:'Premium Girls PG',locality:'University Road',address:'Near MLSU, University Road',price:9500,beds:1,baths:1,area:220,type:'PG',furnishing:'Fully furnished',image:'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80',verified:true,premium:false,highlights:['Meals included','Biometric entry','Laundry','Study zone'],description:'Safe and comfortable PG accommodation with meals, housekeeping and easy access to MLSU and coaching hubs.',owner:'Saraswati Homes',phone:'+91 93522 66111',availableFrom:'2026-08-24',rating:4.4}
];
export const stats = [{label:'Verified homes',value:'850+'},{label:'Udaipur localities',value:'32'},{label:'Avg. response',value:'18 min'},{label:'Broker partners',value:'120+'}];
